[package]
name = "types-reader"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types-reader-core = { path = "../types-reader-core" }
types-reader-macros = { path = "../types-reader-macros" }
